#define AppName "SAM 3.1 Photoshop Selection Backend"
#define AppVersion "0.1.0"
#define Publisher "FR"

[Setup]
AppId={{3E3D3D80-1A69-4EE8-B9F4-A66D979C873A}
AppName={#AppName}
AppVersion={#AppVersion}
AppPublisher={#Publisher}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
DefaultDirName={autopf}\FR\SAM31 Photoshop Selection
DefaultGroupName={#AppName}
DisableProgramGroupPage=yes
MinVersion=10.0
PrivilegesRequired=admin
Compression=lzma2/max
SolidCompression=no
DiskSpanning=yes
DiskSliceSize=2100000000
OutputDir=dist
OutputBaseFilename=SAM31-Backend-Windows-x64
SetupLogging=no
UninstallDisplayIcon={app}\runtime\python.exe
WizardStyle=modern

[Files]
Source: "stage\payload\runtime\*"; DestDir: "{app}\runtime"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "stage\payload\backend\*"; DestDir: "{app}\backend"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "stage\payload\models\*"; DestDir: "{app}\models"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "stage\payload\vendor\sam3\*"; DestDir: "{app}\vendor\sam3"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "stage\payload\licenses\*"; DestDir: "{app}\licenses"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "stage\payload\scripts\SAM31 Image Processor Bridge.jsx"; DestDir: "{code:Photoshop2025Scripts}"; Flags: ignoreversion; Check: Photoshop2025Exists
Source: "stage\payload\scripts\SAM31 Image Processor Bridge.jsx"; DestDir: "{code:Photoshop2026Scripts}"; Flags: ignoreversion; Check: Photoshop2026Exists
Source: "tools\Check-NvidiaGpu.ps1"; Flags: dontcopy

[Code]
var
  RuntimeConfigPath: String;

function Photoshop2025Root(Param: String): String;
begin
  Result := ExpandConstant('{autopf}\Adobe\Adobe Photoshop 2025');
end;

function Photoshop2026Root(Param: String): String;
begin
  Result := ExpandConstant('{autopf}\Adobe\Adobe Photoshop 2026');
end;

function Photoshop2025Scripts(Param: String): String;
begin
  Result := Photoshop2025Root('') + '\Presets\Scripts';
end;

function Photoshop2026Scripts(Param: String): String;
begin
  Result := Photoshop2026Root('') + '\Presets\Scripts';
end;

function Photoshop2025Exists: Boolean;
begin
  Result := FileExists(Photoshop2025Root('') + '\Photoshop.exe');
end;

function Photoshop2026Exists: Boolean;
begin
  Result := FileExists(Photoshop2026Root('') + '\Photoshop.exe');
end;

function RunPowerShell(const ScriptPath: String; var ResultCode: Integer): Boolean;
var
  Parameters: String;
begin
  Parameters := '-NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -File "' + ScriptPath + '"';
  Result := Exec(ExpandConstant('{sys}\WindowsPowerShell\v1.0\powershell.exe'), Parameters, '',
    SW_HIDE, ewWaitUntilTerminated, ResultCode);
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
var
  ResultCode: Integer;
  InstallPath: String;
begin
  Result := '';
  InstallPath := ExpandConstant('{app}');
  if (Pos('%', InstallPath) > 0) or (Pos('!', InstallPath) > 0) or
    (Pos('^', InstallPath) > 0) or (Pos('&', InstallPath) > 0) or
    (Pos('|', InstallPath) > 0) or (Pos('<', InstallPath) > 0) or
    (Pos('>', InstallPath) > 0) then begin
    Result := '安装路径不能包含 % ! ^ & | < >，请另选目录。';
    exit;
  end;
  ExtractTemporaryFile('Check-NvidiaGpu.ps1');
  if (not RunPowerShell(ExpandConstant('{tmp}\Check-NvidiaGpu.ps1'), ResultCode)) or (ResultCode <> 0) then
    Result := '未通过 NVIDIA GPU 检查。需要 Windows 10/11、NVIDIA 驱动和至少 16 GB 级显存。';
end;

procedure WriteRuntimeConfig;
var
  Body: String;
begin
  RuntimeConfigPath := ExpandConstant('{commonappdata}\FR\SAM31 Photoshop Selection\runtime-v1.ini');
  ForceDirectories(ExtractFileDir(RuntimeConfigPath));
  Body := '# Generated by installer' + #13#10 +
    'schemaVersion=1' + #13#10 +
    'installRoot=' + ExpandConstant('{app}') + #13#10 +
    'python=runtime\python.exe' + #13#10 +
    'backend=backend' + #13#10 +
    'model=models\sam3.1_multiplex_fp16.safetensors' + #13#10 +
    'officialSam3=vendor\sam3' + #13#10;
  if not SaveStringToFile(RuntimeConfigPath, Body, False) then
    RaiseException('无法写入机器级运行时配置。');
end;

procedure ValidateRuntime;
var
  ResultCode: Integer;
  Parameters: String;
begin
  Parameters := '-m sam31_backend.preflight --model "' +
    ExpandConstant('{app}\models\sam3.1_multiplex_fp16.safetensors') +
    '" --official-sam3-root "' + ExpandConstant('{app}\vendor\sam3') + '"';
  if (not Exec(ExpandConstant('{app}\runtime\python.exe'), Parameters,
    ExpandConstant('{app}\backend'), SW_HIDE, ewWaitUntilTerminated, ResultCode)) or (ResultCode <> 0) then
    RaiseException('独立运行时自检失败。安装文件、CUDA 驱动或模型可能不完整。');
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then begin
    WriteRuntimeConfig;
    ValidateRuntime;
  end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usPostUninstall then begin
    RuntimeConfigPath := ExpandConstant('{commonappdata}\FR\SAM31 Photoshop Selection\runtime-v1.ini');
    if FileExists(RuntimeConfigPath) then DeleteFile(RuntimeConfigPath);
    RemoveDir(ExtractFileDir(RuntimeConfigPath));
  end;
end;
